[package]
name = "las_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
bevy_flycam = "0.14.1"
bevy_panorbit_camera = "0.19.1"
bincode = "1.3.3"
las = "0.8.8"
nalgebra = "0.33.0"
serde = "1.0.204"
octree = { path = "../octree" }
